function Const_u_case2 = constraints_u_case2(in1,in2,in3,Pd,Smax)
%CONSTRAINTS_U_CASE2
%    Const_u_case2 = CONSTRAINTS_U_CASE2(IN1,IN2,IN3,Pd,Smax)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 09:02:26

du2 = in3(2,:);
u2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x4 = in1(4,:);
et1 = 1.0./(du2.*1.945928467047374e-2+u2.*1.945928467047374e-2).^2;
et2 = (x1.*7.196593168514843e-2+x2.*7.196593168514843e-2-x4.*7.196593168514843e-2+3.36373700923625e-2).*(-1.945928467047374e-2);
Const_u_case2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,et1.*et2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0],[15,3]);
end
