function Pb = Pb_fun(in1,in2,in3)
%Pb_fun
%    Pb = Pb_fun(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 09:02:25

du3 = in3(3,:);
u3 = in2(3,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
Pb = (du3.*3.6e+1+u3.*3.6e+1).*(x5.*(-2.156e-1)+x6+x7./1.0e+1+exp(x5.*-3.5e+1).*1.031+(du3.*(4.0./5.0)+u3.*(4.0./5.0)).*(exp(x5.*(-2.437e+1)).*1.562e-1+7.446e-2)+x5.^2.*1.178e-1-x5.^3.*3.201e-1-7.37e+2./2.0e+2).*-1.2e+1;
end
