function out1 = z_fun(in1,u2,du2)
%Z_FUN
%    OUT1 = Z_FUN(IN1,U2,DU2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 09:02:25

x1 = in1(1,:);
x2 = in1(2,:);
x4 = in1(4,:);
et1 = 1.0./(du2.*1.945928467047374e-2+u2.*1.945928467047374e-2);
et2 = -(x1.*7.196593168514843e-2+x2.*7.196593168514843e-2-x4.*7.196593168514843e-2+3.36373700923625e-2);
out1 = et1.*et2;
end
