function out1 = Battery(in1,u3,du3)
%Battery
%    OUT1 = Battery(IN1,U3,DU3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:15

x5 = in1(1,:);
x6 = in1(2,:);
x7 = in1(3,:);
t2 = du3.*(4.0./5.0);
t3 = u3.*(4.0./5.0);
t4 = x5.*1.351e+3;
t5 = x5.*2.712e+3;
t6 = -t4;
t7 = -t5;
t10 = t2+t3;
t8 = exp(t6);
t9 = exp(t7);
t11 = t9.*6.056e+3;
t12 = t8.*7.529e+2;
t13 = t11-4.475e+3;
t15 = t12-7.036e+2;
t14 = 1.0./t13;
t16 = 1.0./t15;
out1 = [du3.*(-2.61437908496732e-4)-u3./3.825e+3-x5./3.06e+13;-t10.*t16+(t16.*x6)./(exp(x5.*-2.914e+3).*3.208e-1+4.669e-2);-t10.*t14+(t14.*x7)./(exp(x5.*-1.552e+4).*6.603e+1+4.984e-1)];
end
