function lxx = case1_lxx_fun(in1,du1,Ist,dIst,z)
%CASE1_LXX_FUN
%    LXX = CASE1_LXX_FUN(IN1,DU1,Ist,dIst,Z)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:19

t2 = Ist.*1.945928467047374e-2;
t3 = dIst.*1.945928467047374e-2;
t4 = t2+t3;
t5 = 1.0./t4.^2;
t6 = t5.*1.553728596993435e-3;
t7 = -t6;
lxx = reshape([t6,t6,0.0,t7,t6,t6,0.0,t7,0.0,0.0,0.0,0.0,t7,t7,0.0,t6],[4,4]);
end
