function lu = case2_lu_fun(in1,du1,Ist,dIst,z)
%CASE2_LU_FUN
%    LU = CASE2_LU_FUN(IN1,DU1,Ist,dIst,Z)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:21

lu = du1.*2.0e+2;
end
