function luu = case1_luu_fun(in1,du1,Ist,dIst,z)
%CASE1_LUU_FUN
%    LUU = CASE1_LUU_FUN(IN1,DU1,Ist,dIst,Z)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:19

luu = 2.0e+2;
end
