function J = case2_J_fun(in1,du1,Ist,dIst,z)
%case2_J_fun
%    J = case2_J_fun(IN1,DU1,Ist,dIst,Z)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:20

phi1 = in1(1,:);
phi2 = in1(2,:);
phi4 = in1(4,:);
t2 = Ist.*1.945928467047374e-2;
t3 = dIst.*1.945928467047374e-2;
t4 = phi1.*7.196593168514843e-2;
t5 = phi2.*7.196593168514843e-2;
t6 = phi4.*7.196593168514843e-2;
t7 = -t6;
t8 = t2+t3;
t9 = 1.0./t8;
t10 = t4+t5+t7+3.36373700923625e-2;
J = (z+t9.*t10).*(z.*(3.0./2.0e+1)+t9.*t10.*(3.0./2.0e+1))+du1.^2.*1.0e+2;
end
