function lux = case2_lux_fun(in1,du1,Ist,dIst,z)
%CASE2_LUX_FUN
%    LUX = CASE2_LUX_FUN(IN1,DU1,Ist,dIst,Z)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:21

lux = [0.0,0.0,0.0,0.0];
end
