function lx = case2_lx_fun(in1,du1,Ist,dIst,z)
%CASE2_LX_FUN
%    LX = CASE2_LX_FUN(IN1,DU1,Ist,dIst,Z)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:20

phi1 = in1(1,:);
phi2 = in1(2,:);
phi4 = in1(4,:);
t2 = z.*(3.0./2.0e+1);
t3 = Ist.*1.945928467047374e-2;
t4 = dIst.*1.945928467047374e-2;
t5 = phi1.*7.196593168514843e-2;
t6 = phi2.*7.196593168514843e-2;
t7 = phi4.*7.196593168514843e-2;
t8 = -t7;
t9 = t3+t4;
t10 = 1.0./t9;
t11 = t5+t6+t8+3.36373700923625e-2;
t12 = t10.*t11;
t13 = t12+z;
t14 = t12.*(3.0./2.0e+1);
t15 = t2+t14;
t16 = t10.*t13.*1.079488975277227e-2;
t17 = t10.*t15.*7.196593168514843e-2;
t18 = t16+t17;
lx = [t18,t18,0.0,-t18];
end
