function Const_u_case1 = constraints_u_case1(in1,in2,in3,Pd,Smax)
%CONSTRAINTS_U_CASE1
%    Const_u_case1 = CONSTRAINTS_U_CASE1(IN1,IN2,IN3,Pd,Smax)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:16

Const_u_case1 = [0.0;0.0;0.0;0.0;0.0;-1.0;1.0];
end
