function Const_u_case2 = constraints_u_case2(in1,in2,in3,Pd,Smax)
%CONSTRAINTS_U_CASE2
%    Const_u_case2 = CONSTRAINTS_U_CASE2(IN1,IN2,IN3,Pd,Smax)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 08:56:17

Const_u_case2 = [0.0;0.0;0.0;0.0;0.0;-1.0;1.0];
end
